const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');const fs=require('node:fs');
// Small DOM adapter lets the real application handlers run without a browser.
function app(){
 const elements=new Map();
 function element(id){if(!elements.has(id))elements.set(id,{id,value:'',hidden:true,disabled:false,textContent:'',innerHTML:'',tagName:'INPUT',classList:{toggle(){},add(){},remove(){}},style:{},setAttribute(){},focus(){},append(){},remove(){},showModal(){this.open=true;},close(){this.open=false;}});return elements.get(id);}
 const modeButtons=['focus','break','stopwatch'].map(mode=>({...element('mode-'+mode),dataset:{mode}}));
 const minuteButtons=[25,45,60].map(minutes=>({...element('min-'+minutes),dataset:{minutes}}));
 const storage=new Map();let time=100000;
 const D=class extends Date{constructor(...args){super(...(args.length?args:[time]));}static now(){return time;}};
 const context={Date:D,console,Math,JSON,Number,String,Object,Array,Map,Set,Infinity,Promise,document:{title:'',querySelector:s=>element(s),querySelectorAll:s=>s==='[data-mode]'?modeButtons:s==='[data-minutes]'?minuteButtons:[],addEventListener(){},createElement:()=>element('new'),body:{classList:{add(){},remove(){}}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setInterval(){},setTimeout(){},clearTimeout(){}};
 context.window=context;context.globalThis=context;vm.createContext(context);
 for(const f of ['engine.js','activity.js','activity-view.js','app.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),context);
 return {element,context,run:s=>vm.runInContext(s,context),advance:ms=>time+=ms,storage,modeButtons};
}
for(const mode of ['focus','break','stopwatch'])test(`${mode} blocks blank names and starts only after named submission`,()=>{const a=app();a.run(`timer.mode='${mode}'`);a.element('#start').onclick();assert.equal(a.element('#session-dialog').open,true);assert.equal(a.run('timer.running()'),false);a.element('#session-name').value='   ';a.element('#session-form').onsubmit({preventDefault(){}});assert.equal(a.run('timer.running()'),false);a.element('#session-name').value='Chemistry';a.element('#session-form').onsubmit({preventDefault(){}});assert.equal(a.run('timer.running()'),true);assert.equal(a.run('ledger.active.name'),'Chemistry');a.advance(10000);a.element('#start').onclick();a.advance(20000);a.element('#start').onclick();a.advance(5000);a.element('#finish-session').onclick();assert.equal(a.run('ledger.records[0].duration'),15000);assert.equal(a.run('ledger.records.length'),1);assert.equal(a.element('#intention').value,'');assert.equal(a.run('ledger.active'),null);assert.ok(a.storage.has('still-activity-v2'));});
test('reset saves partial activity and duration changes cannot discard active sessions',()=>{const a=app();a.element('#intention').value='Practice';a.element('#start').onclick();a.advance(5000);a.element('#start').onclick();assert.throws(()=>a.run('setDuration(45)'),/Finish and save/);a.element('#reset').onclick();assert.equal(a.run('ledger.records[0].status'),'stopped');assert.equal(a.run('ledger.records[0].duration'),5000);});
test('timer completion records its deadline rather than delayed callback time',()=>{const a=app();a.run('setDuration(1)');a.element('#intention').value='Short study';a.element('#start').onclick();a.advance(120000);a.run('complete()');assert.equal(a.run('ledger.records[0].endedAt'),160000);assert.equal(a.run('ledger.records[0].duration'),60000);assert.equal(a.run('ledger.records[0].status'),'completed');});
test('activity view renders saved sessions, clock filters, and invalid ranges',()=>{const a=app();a.element('#intention').value='Read <chapter>';a.element('#start').onclick();a.advance(15000);a.element('#finish-session').onclick();a.element('#activity-range').value='24h';a.element('#activity-mode').value='all';a.element('#activity-group').value='auto';a.run('renderActivity()');assert.ok(a.element('#history-list').innerHTML.includes('Read &lt;chapter&gt;'));assert.ok(a.element('#analysis-summary').innerHTML.includes('15s'));assert.ok(a.element('#activity-chart').innerHTML.includes('View exact chart values'));a.element('#activity-mode').value='stopwatch';a.run('renderActivity()');assert.ok(a.element('#history-list').innerHTML.includes('No sessions'));a.element('#activity-range').value='rolling';a.element('#range-count').value='0';a.element('#range-unit').value='days';a.run('renderActivity()');assert.equal(a.element('#range-error').hidden,false);assert.equal(a.element('#analysis-content').hidden,true);});
